dist: trusty
language: node_js
node_js:
  - "0.10"
addons:
  postgresql: "9.3"
before_install:
  - npm install -g pg
  - npm install -g grunt
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - psql -c "create user gatewayd_user with password 'password';" -U postgres
  - psql -c "create database gatewayd_db_test with owner gatewayd_user encoding='utf8';" -U postgres
  - export NODE_ENV=test
  - grunt migrate
  - grunt jshint
script:
  - npm test
after_success:
  - npm run coveralls
notifications:
  email:
    false
